### ISSUE TITLE
설계도 

### ISSUE THREAD

**Issue by Ohleesang** [kimnahee1529/KioskProgramming#1]
![KioskProgram drawio](https://github.com/kimnahee1529/KioskProgramming/assets/148442711/d98f6d82-bce4-4af0-bad9-f8590fdc1a23)

https://app.diagrams.net/#G1Um3msBHGag0GChxqO4s3AOLtwMqeODAC

**Comment by kimnahee1529** [comment]
생각하지 못했는데 설계도 버전 1을 확인할 수 있는 용도로 올리는 것은 좋은 것 같습니다! ㅎㅎㅎ
